name: Update Weather API Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  update-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # --- Weather Models (Aeris) ---
      - name: Run fetch_weather.py
        run: |
          python scripts/fetch_weather.py
        env:
          AERIS_ID: ${{ secrets.AERIS_ID }}
          AERIS_SECRET: ${{ secrets.AERIS_SECRET }}

      # --- Tropical Cyclones (TWC) ---
      - name: Run tropical.py
        run: |
          python scripts/tropical.py
        env:
          API_TWC: ${{ secrets.API_TWC }}

      # --- Blended Forecasts (Multiple Points) ---
      - name: Build Blended Forecasts
        run: |
          coords=("33.51,-95.14" "30.63,-87.04" "40.71,-74.00")
          for c in "${coords[@]}"; do
            lat="${c%,*}"
            lon="${c#*,}"
            echo "Blending forecast for $lat,$lon"
            BLEND_LAT="$lat" BLEND_LON="$lon" python scripts/blend_forecast.py
          done
        env:
          API_TWC: ${{ secrets.API_TWC }}

      # --- Build Forecast Index ---
      - name: Build forecast index.json
        run: |
          python scripts/build_forecast_index.py

      # --- Commit & Push ---
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add api/
          git commit -m "Update API data (models, tropical, forecasts)" || echo "No changes to commit"
          git push
