name: Update Weather API Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # --- 1. Fetch Weather Models (HRRR, etc.) ---
      - name: Run fetch_weather.py
        run: |
          python scripts/fetch_weather.py
        env:
          AERIS_ID: ${{ secrets.AERIS_ID }}
          AERIS_SECRET: ${{ secrets.AERIS_SECRET }}

      # --- 2. Fetch Tropical Cyclones ---
      - name: Run tropical.py
        run: |
          python scripts/tropical.py
        env:
          API_TWC: ${{ secrets.API_TWC }}

      # --- 3. Blended Forecast for Multiple Points ---
      - name: Run blend_forecast.py for locations
        run: |
          coords=("33.51,-95.14" "30.63,-87.04" "40.71,-74.00") # Add as many as you want
          for c in "${coords[@]}"; do
            lat=$(echo $c | cut -d',' -f1)
            lon=$(echo $c | cut -d',' -f2)
            echo "Generating forecast for $lat,$lon"
            BLEND_LAT=$lat BLEND_LON=$lon python scripts/blend_forecast.py
          done
        env:
          API_TWC: ${{ secrets.API_TWC }}

      # --- 4. Commit & Push All API Data ---
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add api/
          git commit -m "Update API data (models, tropical, forecasts)"
          git push
